spring.datasource.url=miniproject.mysql.database.azure.com/3306/wishlist
spring.datasource.username=moha4733
spring.datasource.password=Xcp23bdf7479
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
